version: 2

models:
  - name: dim_customers
    description: "Table containing the key data about our customers"
  - name: fct_orders
    description: "Tabel containing orders and successful payments made by our customers"
    columns:
      - name: order_date
        meta:
          dimension:
            label: "Order date"
            type: timestamp
            time_intervals: ['date', 'month', 'year']
      - name: order_value"
        meta:
          metrics:
            total_sales:
              type: "sum"
      
